### ISSUE TITLE
I get the error "The game crashed while initializing game Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered" when trying to start the game.

### ISSUE THREAD

**Issue by Gatoplayer22** [MCModderAnchor/TACZ#41] opened 2024-06-11 22:51 UTC
I have tried to download a previous version but I have the same problem, it is a server with mods where it worked perfectly before.
[crash-2024-06-12_00.11.42-client.txt](https://github.com/user-attachments/files/15795398/crash-2024-06-12_00.11.42-client.txt)

**Comment by 286799714** [comment] 2024-06-12 13:04
There is no useful information in the crash log. It is very likely a mod conflict problem. We have used ModifyArg in the mixin, which is a more compatible way. If there is still a problem, it is beyond our control. You need to find the conflicting mod and delete it.

**Comment by Gatoplayer22** [comment] 2024-06-12 14:55
how can I use the ModifyArg ?

**Comment by 286799714** [comment] 2024-06-13 21:02
You need to find the conflicting mod.

**Comment by 3TUSK** [comment] 2024-06-14 02:04
Technically a duplicate of #7, though I don't have any direct evidence. 

Dev team, please leave this open until #46 (or any other solution) is accepted.

**Closed as completed** 2024-06-14 05:40 UTC
Labels: wontfix
