### ISSUE TITLE
holding attachment in hand triggers error

### ISSUE THREAD

**Issue by dimas1502** [MCModderAnchor/TACZ#85] opened 2024-07-05 15:08 UTC
everytime i hold a weapon attachment in hand, it triggers OpenGL Error 1826: (invalid framebuffer operation)
restarting the game gets rid of it, but will occur again when doing the same

**Comment by WhiteX0il** [comment] 2024-07-07 23:11
Turn off GL errors in options
I mean it doesn't fix the issue, something is wrong, but atleast it's hidden.

**Comment by 286799714** [comment] 2024-07-13 16:51
are you using shaders? try to change a shaderpack or close it

**Comment by dimas1502** [comment] 2024-07-13 16:56
> are you using shaders? try to change a shaderpack or close it

nope, i never used shaders

also i found out it doesn't just happen by holding it, holding a weapon with an attachment also triggers it

i was also using yes steve model btw

**Comment by TartaricAcid** [comment] 2024-07-19 13:13
Unable to reproduce this issue, closed

**Closed as completed by TartaricAcid** 2024-07-19 13:13 UTC
Labels: question
